### ISSUE TITLE
Add support for node 0.12.x

### ISSUE THREAD

**Issue by harianus** [florianheinemann/passwordless-mongostore#8]
It looks like bcrypt install fails, but maybe add a warning in `Readme.md`?

```
$ npm install
> bcrypt@0.7.8 install /node_modules/passwordless-mongostore/node_modules/bcrypt
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
../src/bcrypt_node.cc:54:18: error: no member named 'Dispose' in 'v8::Persistent<v8::Function,
      v8::NonCopyablePersistentTraits<v8::Function> >'
        callback.Dispose();
        ~~~~~~~~ ^
../src/bcrypt_node.cc:128:19: error: unknown type name 'uv_work_t'
void GenSaltAsync(uv_work_t* req) {
                  ^
[...]

  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/bson.node
  SOLINK_MODULE(target) Release/bson.node: Finished
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.7.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.7.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

There is an issue in the bcrypt repository  https://github.com/ncb000gt/node.bcrypt.js/issues/277

**Comment by florianheinemann** [comment]
You're on Windows? :)

You might want to try: https://www.npmjs.com/package/passwordless-mongostore-bcrypt-node

Florian

**Comment by harianus** [comment]
No, I'm on Mac. I have it working with node 0.10.36, so I think you can close this because of a bug not in your code, but in `bcrypt`.

**Comment by 1beb** [comment]
I had a simular issue, these instructions helped me fix it: https://github.com/TooTallNate/node-gyp#installation
